# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', max_length=1000)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=100)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('sem', models.CharField(choices=[('1st', '\u0432\u0435\u0441\u0435\u043d\u043d\u0438\u0439'), ('2nd', '\u043e\u0441\u0435\u043d\u043d\u0438\u0439')], default='1st', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u041a\u0443\u0440\u0441',
                'verbose_name_plural': '\u041a\u0443\u0440\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('field', models.CharField(blank=True, choices=[('\u0415\u0441\u0441\u0442\u0435\u0441\u0442\u0432.', '\u0415\u0441\u0441\u0442\u0435\u0441\u0441\u0442\u0432\u0435\u043d\u043d\u043e-\u043d\u0430\u0443\u0447\u043d\u043e\u0435'), ('\u0413\u0443\u043c', '\u0413\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u043e\u0435'), ('\u0422\u0435\u0445', '\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': '\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442',
                'verbose_name_plural': '\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='\u0424\u0418\u041e')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='myproject.Faculty')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u043e\u0440',
                'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u043e\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myproject.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myproject.Professor'),
        ),
    ]
