# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_auto_20170324_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='place',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u0424\u0418\u041e'),
        ),
    ]
