# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_auto_20170328_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='field',
            field=models.CharField(blank=True, choices=[('\u0415\u0441\u0441\u0442\u0435\u0441\u0442\u0432.', '\u0415\u0441\u0441\u0442\u0435\u0441\u0441\u0442\u0432\u0435\u043d\u043d\u043e-\u043d\u0430\u0443\u0447\u043d\u043e\u0435'), ('\u0413\u0443\u043c', '\u0413\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u043e\u0435'), ('\u0422\u0435\u0445', '\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435')], max_length=255, null=True, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c \u043d\u0430\u0443\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
    ]
